PS bump to sf6
alchemy-fr/phrasea pull request #365
Opened 2023-06-23 14:41 UTC by aynsix

- bump symfony version to symfony 6 for all app in phrasea:

 auth
databox
expose
notify
uploader
and all bundles in lib directory

2023-06-26 13:42 UTC, 4rthem commented on lib/php/remote-auth-bundle/Security/Firewall/RemoteAuthListener.php
> +//class RemoteAuthListener
TODO

2023-06-26 13:43 UTC, 4rthem commented on lib/php/remote-auth-bundle/Security/LoginFormAuthenticator.php
> +        $this->session = $requestStack->getSession();
same

2023-06-26 13:44 UTC, 4rthem commented on lib/php/remote-auth-bundle/Security/Provider/RemoteAuthProvider.php
> +//        $authenticatedToken->setAuthenticated(true);
can be removed

2023-06-26 13:44 UTC, 4rthem commented on lib/php/remote-auth-bundle/Security/RemoteAuthAuthenticator.php
> +        $this->session = $requestStack->getSession();
same

2023-06-26 13:45 UTC, 4rthem commented on lib/php/report-bundle/.php-cs-fixer.cache
gitignore

2023-06-26 13:49 UTC, 4rthem commented on lib/php/report-bundle/.php-cs-fixer.cache
> +{"php":"8.2.4","version":"3.17.0:v3.17.0#3f0ed862f22386c55a767461ef5083bddceeed79","indent":"    ","lineEnding":"\n","rules":{"align_multiline_comment":true,"array_syntax":{"syntax":"short"},"backtic
gitignore

2023-06-26 13:59 UTC, 4rthem requested changes

2023-06-26 13:59 UTC, 4rthem commented on lib/php/storage-bundle/.php-cs-fixer.cache
> +{"php":"8.2.4","version":"3.17.0:v3.17.0#3f0ed862f22386c55a767461ef5083bddceeed79","indent":"    ","lineEnding":"\n","rules":{"align_multiline_comment":true,"array_syntax":{"syntax":"short"},"backtic
gitignore

2023-06-26 13:59 UTC, 4rthem commented on lib/php/test-bundle/.php-cs-fixer.cache
> +{"php":"8.2.4","version":"3.17.0:v3.17.0#3f0ed862f22386c55a767461ef5083bddceeed79","indent":"    ","lineEnding":"\n","rules":{"align_multiline_comment":true,"array_syntax":{"syntax":"short"},"backtic
gitignore

2023-06-26 13:59 UTC, 4rthem commented on lib/php/webhook-bundle/.php-cs-fixer.cache
> +{"php":"8.2.4","version":"3.17.0:v3.17.0#3f0ed862f22386c55a767461ef5083bddceeed79","indent":"    ","lineEnding":"\n","rules":{"align_multiline_comment":true,"array_syntax":{"syntax":"short"},"backtic
gitignore

2023-06-26 13:59 UTC, 4rthem commented on lib/php/workflow-bundle/.php-cs-fixer.cache
> +{"php":"8.2.4","version":"3.17.0:v3.17.0#3f0ed862f22386c55a767461ef5083bddceeed79","indent":"    ","lineEnding":"\n","rules":{"align_multiline_comment":true,"array_syntax":{"syntax":"short"},"backtic
gitignore

2023-06-30 08:46 UTC, aynsix commented on auth/api/config/packages/security.yaml
> -                success_handler: alchemy_admin.logout.success_handler
NO , in sf6 there is no more a success_handler, it's remove as a listener

2023-11-06 11:03 UTC, 4rthem approved these changes

2023-11-06 11:03 UTC, merged