PS-635 Admin filter and configure field
alchemy-fr/phrasea pull request #455
Opened 2024-09-25 15:19 UTC by aynsix

2024-09-25 16:32 UTC, 4rthem requested changes

2024-09-25 16:32 UTC, 4rthem commented on databox/api/src/Controller/Admin/AlternateUrlCrudController.php
> +        yield DateTimeField::new('createdAt');
`createdAt` should not be editable (please apply to others)

```suggestion
        yield DateTimeField::new('createdAt')
            ->hideOnForm();
```

2024-09-26 12:51 UTC, 4rthem requested changes

2024-09-27 10:46 UTC, aynsix commented on databox/api/src/Controller/Admin/BasketAssetCrudController.php
> +            ->add(EntityFilter::new('basket'))
removed, it's not possible with TextFilter

2024-09-27 10:47 UTC, 4rthem approved these changes

2024-09-30 20:09 UTC, merged