PS-720_alpha-tiff-center
alchemy-fr/phrasea pull request #488
Opened 2024-11-19 11:55 UTC by jygaulier

paste layers one by one, centered
### BC-Break
- options `size` and `position` are removed
- option `transparency` is renamed `opacity` to conform to values 0=transparent ; 100=full opaque color

2024-11-20 10:14 UTC, 4rthem requested changes
You should introduce a new Filter, not overriding the Liip's one because it will:
- break BC as you mentioned
- add confusion between documentations
Name suggestion: `BackgroundFillFilter`?

2024-11-25 14:49 UTC, jygaulier commented
nb: liip filter is *not* overwritten (it stays buggy...). we just use our own filter (namespace) with the same name (so no need to change conf).

2024-11-25 14:58 UTC, 4rthem requested changes
I maintain the idea you should find a different name for your filter to avoid confusion with the LiipImage document which we rely on today.

2024-11-25 14:58 UTC, 4rthem commented on lib/php/rendition-factory/src/Transformer/Image/Imagine/BackgroundFilterLoader.php
> +        // DO NOT REMOVE THIS LINE
```suggestion
```

2024-11-25 19:41 UTC, 4rthem approved these changes

2024-11-26 12:39 UTC, merged